#!/bin/bash
x="teste"
menu ()
{
while true $x != "teste"
do
clear
echo "================================================"
tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "SOCKS5 ANDERSONTLS" ; tput sgr0
tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "CRIADOR ANDERSONTLS" ; tput sgr0
echo -e "\033[01;34m•>>>>> (COPIA NAO COMEDIA) <<<<<•\033[01;34m"
echo -e "\033[01;34m•>>>>> (@kroz44) <<<<<•\033[01;34m"
echo ""
echo -e "(1)\033[01;34m•>>>>> (INSTALAR PYTHON3.6 UBUNTU14.04 16.04 \033[01;34m"
echo""
echo -e "(2)\033[01;33m•>>>>> (INSTALAR PYTHON3.6 UBUNTU16.10 17.04)\033[0m"
echo ""
echo -e "(3)\033[01;33m•>>>>> (EXECUTA SOCKS5)\033[0m"
echo ""
echo -e "(4)\033[01;33m•>>>>> (REMOVE PYTHON3.6)\033[0m"
echo""
echo -e "(5)\033[01;33m•>>>>> (PARA SQUID NO UBUNTU 14.04)\033[0m"
echo""
echo -e "(6)\033[01;33m•>>>>> (PARA SQUID NO UBUNTU 14.04)\033[0m"
echo""
echo -e "(7)\033[01;33m•>>>>> (PARA SQUID NO DEBIAM,UBUNTU 16)\033[0m"
echo ""
echo -e "(8)\033[01;33m•>>>>> (SAIR DO SCRIPT)\033[0m"
echo "================================================"

echo "Digite a opção desejada:"
read x
echo "Opção informada ($x)"
echo "================================================"

case "$x" in 


    1)
      echo "INSTALANDO PYTHON3.6 AGUARDE..."
      echo -e "\033[01;33m (TECLE ENTER)\033[0m"
      sudo add-apt-repository ppa:jonathonf/python-3.6
      echo -e "\033[01;33m (TECLE ENTER PARA CONTINUAR)\033[0m"
      read enter
      sudo apt-get update
      sudo apt-get install python3.6 -y
      echo "INSTALANDO COM SUCESSO..."
      sleep 5
      
echo "================================================"
;;
    2)
      echo "INSTALANDO SOCKS"
      sudo apt-get update
      sudo apt-get install python3.6 -y
      sleep 5
echo "================================================"
;;
   3)
      echo "CONFIGURANDO PARA EXECUÇAO AGUARDE..."
      mkdir /etc/proxy5
      cd /etc/proxy5
      touch /etc/proxy5/config.json
      echo "QUAL PORTA DESEJA USA 80,8080,8799 DIGITE A PORTA?..."
      read -p "porta: " porta
      echo "{
      "porta": $porta," >> /etc/proxy5/config.json
      echo "QUAL MESSAGEN NO STATUS 200OK DIGITE..."
      read -p "resposta: " resposta
      echo " "resposta": "$resposta"' >> /etc/proxy5/config.json
      echo "DIGITE O IP DA SUA VPS..."
      read ip
      echo " "servers": "127.0.0.1 $ip" }" >> /etc/proxy5/config.json
      sleep 5 
echo "================================================"
;;
    4)
      echo "REMOVENDO AGUARDE..."
      echo "DIGITE python3.6 PARA DESISTALAR E DE ENTER..."
      read nome
      apt-get remove --purge $nome
      apt-get remove python3.6
      apt-get autoremove
      sleep 5      
echo "================================================"
;;      
     5)  
      echo "PARANDO SQUID..."
      service squid3 stop
      service squid stop
      sleep 5     
echo "================================================"
;;
     6) 
       echo "PARANDO SQUID..."
       /etc/init.d/squid3 stop
       /etc/init.d/squid3 stop
       sleep 5
echo "================================================"
;;
    7) 
      echo "Reparando..."
      dpkg --configure -a
      sleep 5
    
echo "================================================"    
 ;;     
    8)
      echo "saindo..."
         sleep 3
         clear;
         exit;
echo "================================================"
;;

*)
        echo "Opção inválida!"
esac
done

}
menu
