#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

x="teste"
menu ()
{
while true $x != "teste"
do
clear
echo "================================================"
tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "DROPBEAR ANDERSONTLS" ; tput sgr0
tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "CRIADOR ANDERSONTLS" ; tput sgr0
echo -e "\033[01;34m•>>>>> (COPIA NAO COMEDIA) <<<<<•\033[01;34m"
echo -e "\033[01;34m•>>>>> (@kroz44) <<<<<•\033[01;34m"
echo""
echo -e "(1)\033[01;34m•>>>>> (INSTALAR PTHON3.6 UBUNTU14.04 16.04 \033[01;34m"
echo""
echo -e "(2)\033[01;33m•>>>>> (INSTALAR PTHON3.6 UBUNTU16.10 17.04)\033[0m"
echo ""
echo -e "(3)\033[01;33m•>>>>> (EXECUTA SOCKS5)\033[0m"
echo ""
echo -e "(4)\033[01;33m•>>>>> (REMOVE PYTHON3.64)\033[0m"
echo""
echo -e "(5)\033[01;33m•>>>>> (PARA SQUID NO UBUNTU 14.04)\033[0m"
echo""
echo -e "(6)\033[01;33m•>>>>> (PARA SQUID NO DEBIAM,UBUNTU 16)\033[0m"
echo""
echo -e "(7)\033[01;33m•>>>>> (CORRIGIR ERROS DO SERVIDOR)\033[0m"
echo""
echo -e "(8)\033[01;33m•>>>>> (SAIR DO SCRIPT)\033[0m"
echo ""
echo "================================================"

echo "Digite a opção desejada:"
read x
echo "Opção informada ($x)"
echo "================================================"

case "$x" in 


    1)
      echo "INSTALANDO PYTHON3.6 AGUARDE..."
      sudo add-apt-repository ppa:jonathonf/python-3.6
      read -p 
      sudo apt-get update
      sudo apt-get install python3.6 -Y
      sleep 5
      
echo "================================================"
;;
    2)
      echo "INSTALANDO SOCKS"
      sudo apt-get update
      sudo apt-get install python3.6
      sleep 5
echo "================================================"
;;
   3)
      echo "REMOVENDO AGUARDE..."
      echo "DIGITE python3.6 PARA DESISTALAR E DE ENTER..."
      read nome
      apt-get remove --purge $nome
      apt-get remove python3.6
      apt-get autoremove
      sleep 5
echo "================================================"
;;
   4)
      echo "REMOVENDO AGUARDE..."
      echo "DIGITE python3.6 PARA DESISTALAR E DE ENTER..."
      read nome
      apt-get remove --purge $nome
      apt-get remove python3.6
      apt-get autoremove
      sleep 5
echo "================================================"
;;      
   5)
      echo "PARANDO SQUID..."
      service squid3 stop
      service squid stop
      sleep 5
echo "================================================"
;;      
   6)  
      echo "PARANDO SQUID..."
      /etc/init.d/squid3 stop
      /etc/init.d/squid3 stop
      sleep 5
echo "================================================"
;;
   7) 
      echo "Reparando..."
      dpkg --configure -a
      sleep 5

echo "================================================"
 ;;     
    8)
      echo "saindo..."
      sleep 5
      clear;
      exit;
echo "================================================"
;;

*)
        echo "Opção inválida!"
esac
done

}
menu







     
